// FAQ page content (/resources/faq)

export interface FaqQuestion {
  question: string;
  answer: string;
}

export interface FaqCategory {
  id: string;
  label: string;
  questions: FaqQuestion[];
}

export const FAQ_PAGE = {
  title: 'Frequently Asked Questions',
  subtitle: 'Find answers to common questions about the Vehicle Loan Scheme',
  meta: {
    title: 'FAQ | Vehicle Loan Scheme',
    description:
      'Frequently asked questions about the Oyo State Vehicle Loan Scheme for beneficiaries, MDA officers, and general enquiries.',
  },
};

export const FAQ_CATEGORIES: FaqCategory[] = [
  {
    id: 'beneficiaries',
    label: 'For Beneficiaries',
    questions: [
      {
        question: 'How do I check my loan balance?',
        answer:
          'Once the Beneficiary Portal launches in Phase 2, you will be able to log in and view your current loan balance, repayment history, and remaining tenure. Until then, please contact your MDA officer or the Car Loan Department for balance enquiries.',
      },
      {
        question: 'What happens when my loan is paid off?',
        answer:
          'When your loan balance reaches zero, VLPRS automatically generates an Auto-Stop Certificate and notifies your MDA to cease payroll deductions. No manual intervention is required from you or your MDA officer.',
      },
      {
        question: 'What is an Auto-Stop Certificate?',
        answer:
          'An Auto-Stop Certificate is an official document generated by VLPRS confirming that your vehicle loan has been fully repaid. It serves as clearance documentation and instructs your MDA to stop deducting loan repayments from your salary.',
      },
      {
        question: 'How are my repayments calculated?',
        answer:
          'Your monthly repayment is calculated based on your approved loan amount and tenure (standard 60 months) at the scheme interest rate of 13.33% per annum. The system computes the principal portion plus interest for each month. You can view the full schedule once the Beneficiary Portal is available.',
      },
      {
        question: 'What is an Expression of Interest?',
        answer:
          'An Expression of Interest (EOI) is a formal submission indicating your desire to apply for a vehicle loan under the scheme. It is not an application or approval; it registers your interest for administrative processing and committee review.',
      },
      {
        question: 'Can I pay off my loan early?',
        answer:
          'Yes. The scheme supports early principal settlement. You can make a lump-sum payment to settle your remaining principal balance at any time. VLPRS computes the exact settlement amount and generates a clearance certificate upon completion.',
      },
    ],
  },
  {
    id: 'mda-officers',
    label: 'For MDA Officers',
    questions: [
      {
        question: 'How do I submit monthly deduction data?',
        answer:
          'Log into the VLPRS portal, navigate to the Submissions section, and upload your monthly CSV file containing deduction records for all beneficiaries in your MDA. The system validates the file and provides a confirmation summary.',
      },
      {
        question: 'What is the 8-field CSV format?',
        answer:
          'The CSV file contains 8 fields: Staff ID, Month, Amount Deducted, Payroll Batch Reference, MDA Code, Event Flag, Event Effective Date, and Deduction Cessation Reason. A downloadable template with example data is available on the Downloads page.',
      },
      {
        question: 'What happens if I make an error in my submission?',
        answer:
          'VLPRS validates your CSV on upload and reports any errors before the submission is finalised. If an error is discovered after submission, contact the Car Loan Department to initiate a correction. The system maintains an audit trail of all changes.',
      },
      {
        question: 'When is the submission deadline?',
        answer:
          'Monthly deduction data must be submitted by the 28th of each month. Reminder notifications are sent at T-3 days (25th), and overdue alerts are generated after the deadline. Timely submission ensures accurate record-keeping across all MDAs.',
      },
      {
        question: 'What does the Event Flag field mean?',
        answer:
          'The Event Flag indicates any employment event affecting the beneficiary during that month. Common values include NONE (normal deduction), RETIREMENT, TRANSFER, TERMINATION, and DEATH. When set to a value other than NONE, the Event Effective Date field becomes required.',
      },
    ],
  },
  {
    id: 'general',
    label: 'General',
    questions: [
      {
        question: 'What is VLPRS?',
        answer:
          'VLPRS (Vehicle Loan Processing & Receivables System) is a digital platform administered by the Accountant-General\'s Office for managing the Oyo State Vehicle Loan Scheme. It provides centralised record-keeping, automated computation, and transparent reporting across all participating MDAs.',
      },
      {
        question: 'Who administers the scheme?',
        answer:
          'The Vehicle Loan Scheme is administered by the Accountant-General\'s Office under the authority of the Oyo State Government. The Car Loan Department handles day-to-day operations, and the Vehicle Loan Committee is responsible for approving loan applications.',
      },
      {
        question: 'How is my data protected?',
        answer:
          'VLPRS handles personal data in alignment with the Nigeria Data Protection Regulation (NDPR). Access is role-based and limited to authorised personnel. All data is encrypted at rest (AES-256) and in transit (TLS 1.2+), with comprehensive audit logging of all access and changes.',
      },
      {
        question: 'Does VLPRS approve or reject loans?',
        answer:
          'No. VLPRS is an administrative support system that records and administers decisions. All loan approvals, rejections, and policy determinations remain the exclusive responsibility of the Vehicle Loan Committee.',
      },
      {
        question: 'How can I contact support?',
        answer:
          'For enquiries, contact the Car Loan Department at the Accountant-General\'s Office, Secretariat, Agodi, Ibadan. You can also email carloan@oyo.gov.ng or visit the Help & Support page for additional guidance.',
      },
    ],
  },
];
