services:
  server:
    build:
      context: .
      dockerfile: Dockerfile.server
      target: production
    ports:
      - "3001:3001"
    environment:
      - DATABASE_URL=${DATABASE_URL}
      - NODE_ENV=production
      - PORT=3001
      - JWT_SECRET=${JWT_SECRET}
      - JWT_EXPIRY=${JWT_EXPIRY}
      - REFRESH_TOKEN_EXPIRY=${REFRESH_TOKEN_EXPIRY}
    restart: unless-stopped

  client:
    build:
      context: .
      dockerfile: Dockerfile.client
      target: production
    ports:
      - "80:80"
    depends_on:
      - server
    restart: unless-stopped
