services:
  db:
    image: postgres:17-alpine
    environment:
      POSTGRES_USER: vlprs
      POSTGRES_PASSWORD: vlprs_dev
      POSTGRES_DB: vlprs_dev
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U vlprs -d vlprs_dev"]
      interval: 5s
      timeout: 5s
      retries: 5

  server:
    build:
      context: .
      dockerfile: Dockerfile.server
      target: development
    ports:
      - "3001:3001"
    volumes:
      - ./apps/server:/app/apps/server
      - ./packages/shared:/app/packages/shared
      - /app/node_modules
    environment:
      - DATABASE_URL=postgresql://vlprs:vlprs_dev@db:5432/vlprs_dev
      - NODE_ENV=development
      - PORT=3001
    depends_on:
      db:
        condition: service_healthy
    command: pnpm --filter server dev

  client:
    build:
      context: .
      dockerfile: Dockerfile.client
      target: development
    ports:
      - "5173:5173"
    volumes:
      - ./apps/client:/app/apps/client
      - ./packages/shared:/app/packages/shared
      - /app/node_modules
    environment:
      - VITE_API_URL=http://localhost:3001/api
    depends_on:
      - server
    command: pnpm --filter client dev --host

volumes:
  pgdata:
