/**
 * Authoritative MDA list — 63 entries from docs/mdas_list.txt.
 * Single source of truth for MDA reference data across the monorepo.
 */
export const MDA_LIST = [
  { name: 'Oyo State Hospital Management Board', code: 'OYSHMB', abbreviation: 'OYSHMB' },
  { name: 'Ministry of Finance', code: 'FINANCE', abbreviation: 'Finance' },
  { name: 'Agricultural Credit Corporation of Oyo State', code: 'ACCOS', abbreviation: 'ACCOS' },
  { name: 'Library Board', code: 'LIBRARY', abbreviation: 'Library Board' },
  { name: 'Ministry of Local Government and Chieftaincy Matters', code: 'LOCAL GOVERNMENT', abbreviation: 'Local Govt' },
  { name: 'Ministry of Information', code: 'INFORMATION', abbreviation: 'Information' },
  { name: 'Public Complaints Commission', code: 'PCC', abbreviation: 'PCC' },
  { name: 'Bureau of Statistics', code: 'STATISTICS', abbreviation: 'Statistics' },
  { name: 'Board for Technical and Vocational Education', code: 'BOTAVED', abbreviation: 'BOTAVED' },
  { name: 'Ministry of Special Duties', code: 'SPECIAL DUTIES', abbreviation: 'Special Duties' },
  { name: 'Oyo State Housing Corporation', code: 'HOUSING', abbreviation: 'Housing Corp' },
  { name: 'Local Government Audit Commission', code: 'LOCAL GOVERNMENT AUDIT', abbreviation: 'LG Audit' },
  { name: 'Office of the Surveyor General', code: 'SURVEYOR GENERAL', abbreviation: 'Surveyor General' },
  { name: 'Teaching Service Commission', code: 'TESCOM', abbreviation: 'TESCOM' },
  { name: 'Ministry of Women Affairs', code: 'WOMEN AFFAIRS', abbreviation: 'Women Affairs' },
  { name: 'Oyo State Legislature', code: 'LEGISLATURE', abbreviation: 'Legislature' },
  { name: 'Broadcasting Corporation of Oyo State', code: 'BCOS', abbreviation: 'BCOS' },
  { name: 'Ministry of Environment', code: 'ENVIRONMENT', abbreviation: 'Environment' },
  { name: 'State Universal Basic Education Board', code: 'SUBEB', abbreviation: 'SUBEB' },
  { name: 'Oyo State Sports Council', code: 'SPORTS COUNCIL', abbreviation: 'Sports Council' },
  { name: 'House of Assembly Commission', code: 'ASSEMBLY COMMISSION', abbreviation: 'Assembly Commission' },
  { name: 'Oyo State Water Corporation', code: 'WATER CORPORATION', abbreviation: 'Water Corp' },
  { name: 'Board of Internal Revenue', code: 'BIR', abbreviation: 'BIR' },
  { name: 'Ministry of Budget and Economic Planning', code: 'BUDGET AND PLANNING', abbreviation: 'Budget & Planning' },
  { name: 'Oyo State Judicial Service Commission', code: 'JUDICIAL COMMISSION', abbreviation: 'Judicial Commission' },
  { name: 'Ministry of Health', code: 'HEALTH', abbreviation: 'Health' },
  { name: 'College of Health Sciences', code: 'HEALTH COLLEGE', abbreviation: 'Health College' },
  { name: 'College of Nursing and Midwifery', code: 'NURSING AND MIDWIFERY', abbreviation: 'Nursing & Midwifery' },
  { name: 'Oyo State Agency for Adult and Non-Formal Education', code: 'AANFE', abbreviation: 'AANFE' },
  { name: 'Ministry of Energy and Mineral Resources', code: 'ENERGY RESOURCES', abbreviation: 'Energy Resources' },
  { name: 'Oyo State Health Insurance Agency', code: 'OYSHIA', abbreviation: 'OYSHIA' },
  { name: 'Ministry of Establishment', code: 'ESTABLISHMENT', abbreviation: 'Establishment' },
  { name: 'Oyo State Investment, Public and Private Partnership Agency', code: 'OYSIPA', abbreviation: 'OYSIPA' },
  { name: 'Oyo State Road Traffic Management Agency', code: 'OYRTMA', abbreviation: 'OYRTMA' },
  { name: 'Oyo State Independent Electoral Commission', code: 'OYSIEC', abbreviation: 'OYSIEC' },
  { name: 'Oyo State Primary Healthcare Board', code: 'OYSPHB', abbreviation: 'OYSPHB' },
  { name: 'Oyo State Mineral Development Agency', code: 'OYSMDA', abbreviation: 'OYSMDA' },
  { name: 'Ministry of Lands and Housing', code: 'LANDS AND HOUSING', abbreviation: 'Lands & Housing' },
  { name: 'Ministry of Education', code: 'EDUCATION', abbreviation: 'Education' },
  { name: 'Oyo State Advertising Agency', code: 'OYSAA', abbreviation: 'OYSAA' },
  { name: 'Oyo State Rural Electrification Board', code: 'OYSREB', abbreviation: 'OYSREB' },
  { name: "Governor's Office", code: 'GOVERNOR OFFICE', abbreviation: "Governor's Office" },
  { name: "Accountant General's Office", code: 'ACCOUNTANT GENERAL', abbreviation: 'Accountant General' },
  { name: 'Ministry of Arts and Culture', code: 'ARTS AND CULTURE', abbreviation: 'Arts & Culture' },
  { name: 'Oyo State High Court', code: 'HIGH COURT', abbreviation: 'High Court' },
  { name: 'Oyo State Agency for Youth Development', code: 'YOUTH DEVELOPMENT', abbreviation: 'Youth Development' },
  { name: 'Oyo State Road Maintenance Agency', code: 'OYSROMA', abbreviation: 'OYSROMA' },
  { name: 'Head of Service Office', code: 'HOS', abbreviation: 'HOS' },
  { name: 'Oyo State Government Printing Press', code: 'PRINTING PRESS', abbreviation: 'Printing Press' },
  { name: 'Cocoa Development Unit', code: 'CDU', abbreviation: 'CDU' },
  { name: 'Auditor General of Oyo State', code: 'AUDITOR GENERAL', abbreviation: 'Auditor General' },
  { name: 'Ministry of Works and Transport', code: 'WORKS AND TRANSPORT', abbreviation: 'Works & Transport' },
  { name: 'Oyo State Agricultural Development Agency', code: 'OYSADA', abbreviation: 'OYSADA' },
  { name: 'Civil Service Commission', code: 'CSC', abbreviation: 'CSC' },
  { name: 'Ministry of Youth and Sports', code: 'YOUTH AND SPORTS', abbreviation: 'Youth & Sports' },
  { name: 'Ministry of Trade, Investment and Cooperatives', code: 'TRADE', abbreviation: 'Trade' },
  { name: 'Oyo State Pensions Board', code: 'PENSIONS BOARD', abbreviation: 'Pensions Board' },
  { name: 'Ministry of Justice', code: 'JUSTICE', abbreviation: 'Justice' },
  { name: 'Customary Court of Appeal', code: 'CCA', abbreviation: 'CCA' },
  { name: 'Ministry of Agriculture', code: 'AGRICULTURE', abbreviation: 'Agriculture' },
  { name: 'Audit Service Commission', code: 'AUDIT SERVICE COMMISSION', abbreviation: 'Audit Service' },
  { name: 'Ministry of Culture and Tourism', code: 'CULTURE AND TOURISM', abbreviation: 'Culture & Tourism' },
  { name: 'Oyo State Fire Service Agency', code: 'FIRE', abbreviation: 'Fire Service' },
] as const;

/** Derived type for all valid MDA codes. */
export type MdaCode = (typeof MDA_LIST)[number]['code'];

/** Lookup an MDA entry by code. */
export const mdaByCode = (code: string) => MDA_LIST.find((m) => m.code === code);

/**
 * Legacy code aliases — maps old (incorrect) codes to canonical MDA codes.
 * Used by seed logic and MDA resolution.
 */
export const MDA_ALIASES = [
  { oldCode: 'HLT', newCode: 'HEALTH' },
  { oldCode: 'EDU', newCode: 'EDUCATION' },
  { oldCode: 'WKT', newCode: 'WORKS AND TRANSPORT' },
  { oldCode: 'MOF', newCode: 'FINANCE' },
  { oldCode: 'MOA', newCode: 'AGRICULTURE' },
  { oldCode: 'MOJ', newCode: 'JUSTICE' },
  { oldCode: 'MTI', newCode: 'TRADE' },
  { oldCode: 'MIC', newCode: 'INFORMATION' },
  { oldCode: 'MEN', newCode: 'ENVIRONMENT' },
  { oldCode: 'MWA', newCode: 'WOMEN AFFAIRS' },
  { oldCode: 'MLH', newCode: 'LANDS AND HOUSING' },
  { oldCode: 'MLG', newCode: 'LOCAL GOVERNMENT' },
  { oldCode: 'MBE', newCode: 'BUDGET AND PLANNING' },
  { oldCode: 'MET', newCode: 'ESTABLISHMENT' },
  { oldCode: 'MYS', newCode: 'YOUTH AND SPORTS' },
  { oldCode: 'MER', newCode: 'ENERGY RESOURCES' },
  { oldCode: 'MSD', newCode: 'SPECIAL DUTIES' },
  { oldCode: 'IRS', newCode: 'BIR' },
  { oldCode: 'TSC', newCode: 'TESCOM' },
  { oldCode: 'HMB', newCode: 'OYSHMB' },
  { oldCode: 'OSBC', newCode: 'BCOS' },
  { oldCode: 'SWB', newCode: 'SPORTS COUNCIL' },
  { oldCode: 'UBE', newCode: 'SUBEB' },
  { oldCode: 'LIB', newCode: 'LIBRARY' },
  { oldCode: 'FRE', newCode: 'FIRE' },
  { oldCode: 'PHC', newCode: 'OYSPHB' },
  { oldCode: 'RMC', newCode: 'OYSROMA' },
  { oldCode: 'AGA', newCode: 'ACCOUNTANT GENERAL' },
  { oldCode: 'OHS', newCode: 'HOS' },
  { oldCode: 'GOV', newCode: 'GOVERNOR OFFICE' },
  { oldCode: 'OAG', newCode: 'AUDITOR GENERAL' },
  { oldCode: 'JSC', newCode: 'JUDICIAL COMMISSION' },
  { oldCode: 'SHA', newCode: 'ASSEMBLY COMMISSION' },
  { oldCode: 'WCA', newCode: 'WATER CORPORATION' },
  { oldCode: 'TVT', newCode: 'BOTAVED' },
  { oldCode: 'TRB', newCode: 'OYRTMA' },
  { oldCode: 'PCR', newCode: 'PENSIONS BOARD' },
  { oldCode: 'ASA', newCode: 'OYSADA' },
] as const;
