-- VLPRS Production MDA Seed (63 MDAs)
-- Safe to run multiple times: ON CONFLICT DO NOTHING
BEGIN;
INSERT INTO mdas (id, name, code, abbreviation, is_active, created_at, updated_at) VALUES
(gen_random_uuid(), 'Oyo State Hospital Management Board', 'OYSHMB', 'OYSHMB', true, NOW(), NOW()),
(gen_random_uuid(), 'Ministry of Finance', 'FINANCE', 'Finance', true, NOW(), NOW()),
(gen_random_uuid(), 'Agricultural Credit Corporation of Oyo State', 'ACCOS', 'ACCOS', true, NOW(), NOW()),
(gen_random_uuid(), 'Library Board', 'LIBRARY', 'Library Board', true, NOW(), NOW()),
(gen_random_uuid(), 'Ministry of Local Government and Chieftaincy Matters', 'LOCAL GOVERNMENT', 'Local Govt', true, NOW(), NOW()),
(gen_random_uuid(), 'Ministry of Information', 'INFORMATION', 'Information', true, NOW(), NOW()),
(gen_random_uuid(), 'Public Complaints Commission', 'PCC', 'PCC', true, NOW(), NOW()),
(gen_random_uuid(), 'Bureau of Statistics', 'STATISTICS', 'Statistics', true, NOW(), NOW()),
(gen_random_uuid(), 'Board for Technical and Vocational Education', 'BOTAVED', 'BOTAVED', true, NOW(), NOW()),
(gen_random_uuid(), 'Ministry of Special Duties', 'SPECIAL DUTIES', 'Special Duties', true, NOW(), NOW()),
(gen_random_uuid(), 'Oyo State Housing Corporation', 'HOUSING', 'Housing Corp', true, NOW(), NOW()),
(gen_random_uuid(), 'Local Government Audit Commission', 'LOCAL GOVERNMENT AUDIT', 'LG Audit', true, NOW(), NOW()),
(gen_random_uuid(), 'Office of the Surveyor General', 'SURVEYOR GENERAL', 'Surveyor General', true, NOW(), NOW()),
(gen_random_uuid(), 'Teaching Service Commission', 'TESCOM', 'TESCOM', true, NOW(), NOW()),
(gen_random_uuid(), 'Ministry of Women Affairs', 'WOMEN AFFAIRS', 'Women Affairs', true, NOW(), NOW()),
(gen_random_uuid(), 'Oyo State Legislature', 'LEGISLATURE', 'Legislature', true, NOW(), NOW()),
(gen_random_uuid(), 'Broadcasting Corporation of Oyo State', 'BCOS', 'BCOS', true, NOW(), NOW()),
(gen_random_uuid(), 'Ministry of Environment', 'ENVIRONMENT', 'Environment', true, NOW(), NOW()),
(gen_random_uuid(), 'State Universal Basic Education Board', 'SUBEB', 'SUBEB', true, NOW(), NOW()),
(gen_random_uuid(), 'Oyo State Sports Council', 'SPORTS COUNCIL', 'Sports Council', true, NOW(), NOW()),
(gen_random_uuid(), 'House of Assembly Commission', 'ASSEMBLY COMMISSION', 'Assembly Commission', true, NOW(), NOW()),
(gen_random_uuid(), 'Oyo State Water Corporation', 'WATER CORPORATION', 'Water Corp', true, NOW(), NOW()),
(gen_random_uuid(), 'Board of Internal Revenue', 'BIR', 'BIR', true, NOW(), NOW()),
(gen_random_uuid(), 'Ministry of Budget and Economic Planning', 'BUDGET AND PLANNING', 'Budget & Planning', true, NOW(), NOW()),
(gen_random_uuid(), 'Oyo State Judicial Service Commission', 'JUDICIAL COMMISSION', 'Judicial Commission', true, NOW(), NOW()),
(gen_random_uuid(), 'Ministry of Health', 'HEALTH', 'Health', true, NOW(), NOW()),
(gen_random_uuid(), 'College of Health Sciences', 'HEALTH COLLEGE', 'Health College', true, NOW(), NOW()),
(gen_random_uuid(), 'College of Nursing and Midwifery', 'NURSING AND MIDWIFERY', 'Nursing & Midwifery', true, NOW(), NOW()),
(gen_random_uuid(), 'Oyo State Agency for Adult and Non-Formal Education', 'AANFE', 'AANFE', true, NOW(), NOW()),
(gen_random_uuid(), 'Ministry of Energy and Mineral Resources', 'ENERGY RESOURCES', 'Energy Resources', true, NOW(), NOW()),
(gen_random_uuid(), 'Oyo State Health Insurance Agency', 'OYSHIA', 'OYSHIA', true, NOW(), NOW()),
(gen_random_uuid(), 'Ministry of Establishment', 'ESTABLISHMENT', 'Establishment', true, NOW(), NOW()),
(gen_random_uuid(), 'Oyo State Investment, Public and Private Partnership Agency', 'OYSIPA', 'OYSIPA', true, NOW(), NOW()),
(gen_random_uuid(), 'Oyo State Road Traffic Management Agency', 'OYRTMA', 'OYRTMA', true, NOW(), NOW()),
(gen_random_uuid(), 'Oyo State Independent Electoral Commission', 'OYSIEC', 'OYSIEC', true, NOW(), NOW()),
(gen_random_uuid(), 'Oyo State Primary Healthcare Board', 'OYSPHB', 'OYSPHB', true, NOW(), NOW()),
(gen_random_uuid(), 'Oyo State Mineral Development Agency', 'OYSMDA', 'OYSMDA', true, NOW(), NOW()),
(gen_random_uuid(), 'Ministry of Lands and Housing', 'LANDS AND HOUSING', 'Lands & Housing', true, NOW(), NOW()),
(gen_random_uuid(), 'Ministry of Education', 'EDUCATION', 'Education', true, NOW(), NOW()),
(gen_random_uuid(), 'Oyo State Advertising Agency', 'OYSAA', 'OYSAA', true, NOW(), NOW()),
(gen_random_uuid(), 'Oyo State Rural Electrification Board', 'OYSREB', 'OYSREB', true, NOW(), NOW()),
(gen_random_uuid(), 'Governor''s Office', 'GOVERNOR OFFICE', 'Governor''s Office', true, NOW(), NOW()),
(gen_random_uuid(), 'Accountant General''s Office', 'ACCOUNTANT GENERAL', 'Accountant General', true, NOW(), NOW()),
(gen_random_uuid(), 'Ministry of Arts and Culture', 'ARTS AND CULTURE', 'Arts & Culture', true, NOW(), NOW()),
(gen_random_uuid(), 'Oyo State High Court', 'HIGH COURT', 'High Court', true, NOW(), NOW()),
(gen_random_uuid(), 'Oyo State Agency for Youth Development', 'YOUTH DEVELOPMENT', 'Youth Development', true, NOW(), NOW()),
(gen_random_uuid(), 'Oyo State Road Maintenance Agency', 'OYSROMA', 'OYSROMA', true, NOW(), NOW()),
(gen_random_uuid(), 'Head of Service Office', 'HOS', 'HOS', true, NOW(), NOW()),
(gen_random_uuid(), 'Oyo State Government Printing Press', 'PRINTING PRESS', 'Printing Press', true, NOW(), NOW()),
(gen_random_uuid(), 'Cocoa Development Unit', 'CDU', 'CDU', true, NOW(), NOW()),
(gen_random_uuid(), 'Auditor General of Oyo State', 'AUDITOR GENERAL', 'Auditor General', true, NOW(), NOW()),
(gen_random_uuid(), 'Ministry of Works and Transport', 'WORKS AND TRANSPORT', 'Works & Transport', true, NOW(), NOW()),
(gen_random_uuid(), 'Oyo State Agricultural Development Agency', 'OYSADA', 'OYSADA', true, NOW(), NOW()),
(gen_random_uuid(), 'Civil Service Commission', 'CSC', 'CSC', true, NOW(), NOW()),
(gen_random_uuid(), 'Ministry of Youth and Sports', 'YOUTH AND SPORTS', 'Youth & Sports', true, NOW(), NOW()),
(gen_random_uuid(), 'Ministry of Trade, Investment and Cooperatives', 'TRADE', 'Trade', true, NOW(), NOW()),
(gen_random_uuid(), 'Oyo State Pensions Board', 'PENSIONS BOARD', 'Pensions Board', true, NOW(), NOW()),
(gen_random_uuid(), 'Ministry of Justice', 'JUSTICE', 'Justice', true, NOW(), NOW()),
(gen_random_uuid(), 'Customary Court of Appeal', 'CCA', 'CCA', true, NOW(), NOW()),
(gen_random_uuid(), 'Ministry of Agriculture', 'AGRICULTURE', 'Agriculture', true, NOW(), NOW()),
(gen_random_uuid(), 'Audit Service Commission', 'AUDIT SERVICE COMMISSION', 'Audit Service', true, NOW(), NOW()),
(gen_random_uuid(), 'Ministry of Culture and Tourism', 'CULTURE AND TOURISM', 'Culture & Tourism', true, NOW(), NOW()),
(gen_random_uuid(), 'Oyo State Fire Service Agency', 'FIRE', 'Fire Service', true, NOW(), NOW())
ON CONFLICT (code) DO NOTHING;
COMMIT;
SELECT count(*) AS mda_count FROM mdas;
